version: '2.2'

services:
  api:
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=[2001:a:a:b::20]
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - HOST=localhost
    expose:
      - "1337"
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
      - /usr/src/api/strapi-app/node_modules
    networks:
      strapinet:
        # ipv4_address: 192.168.30.11
        ipv6_address: 2001:a:a:b::30
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    expose:
      - "27017"
    volumes:
      - ./db:/data/db
    command: mongod --ipv6 --bind_ip_all
    networks:
      strapinet:
        # ipv4_address: 192.168.30.12
        ipv6_address: 2001:a:a:b::20
    restart: always
## https://www.sohamkamani.com/blog/2016/06/30/docker-mongo-replica-set/
## --slaveok true  --replSet strapi

  nginx:
    build: ./nginx/
    depends_on:
      - api
    image: nginx:alpine
    restart: always
    ports:
      - 1337:1337
      - 27017:27017
      - 80:80
    networks:
      strapinet:
        ipv6_address: 2001:a:a:b::22
      nginxnet:
        ipv6_address: 2001:30::30

networks:
  strapinet:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        # - subnet: 192.168.30.0/24
        - subnet: 2001:a:a:b::/64
  nginxnet:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        # - subnet: 192.168.30.0/24
        - subnet: 2001:30::/64
